version: "3.8"

services:
  nest_server:
    depends_on:
      - mysql_server
      - redis_server
    container_name: nest_server
    restart: always
    build:
      context: ./nest-server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEST_SERVER_PORT=${NEST_DOCKER_PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - RESET_PASSWORD_TOKEN_SECRET=${RESET_PASSWORD_TOKEN_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_DOCKER_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - task_management_api_networks
    stdin_open: true
    tty: true
    ports:
      - ${NEST_LOCAL_PORT}:${NEST_DOCKER_PORT}

  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    networks:
      - task_management_api_networks

  redis_server:
    image: redis:7.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis_server
    restart: always
    env_file:
      - ./.env
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    volumes:
      - ./data/redis-data:/data
    networks:
      - task_management_api_networks

networks:
  task_management_api_networks:
    driver: bridge
