export enum EMetadataKey {
  IS_PUBLIC_ROUTE = 'IS_PUBLIC_ROUTE',
  CHECK_PERMISSION = 'CHECK_PERMISSION'
}

export enum ETokenExpiration {
  ACCESS_TOKEN = 2 * 60,
  REFRESH_TOKEN = 7 * 24 * 60 * 60,
  RESET_PASSWORD_TOKEN = 5 * 60
}

export enum ELoginExceptionErrorType {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REQUIRED_2FA_OTP = 'REQUIRED_2FA_OTP',
  INVALID_2FA_OTP = 'INVALID_2FA_OTP',
  REQUIRED_INITIALIZE_PASSWORD = 'REQUIRED_INITIALIZE_PASSWORD'
}
